trial for 20 Oct 2024

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,7 +14,7 @@ script:
   # Scan Docker image with Trivy and save the report in JSON format
   - trivy --debug image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy-report.json trivy-travis:latest || true
   # Display contents of the report if it exists
-  - cat trivy-report.json || echo "No report generated by Trivy."
+  #- cat trivy-report.json || echo "No report generated by Trivy."
   # Correct Permissions
   - chmod 644 trivy-report.json
 
@@ -36,5 +36,5 @@ after_script:
         -F "tags=sample" \
         --max-time 300 || echo "Failed to upload the report."
     else
-      echo "Report file not found, skipping upload."
+      echo "Connection fail, skipping upload."
     fi
