final1

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,21 +12,21 @@ script:
   # Build Docker image
   - docker build -t trivy-travis:latest .
   # Scan Docker image with Trivy and save the report in JSON format
-  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy-report.json trivy-travis:latest || true
+  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy-travis-report.json trivy-travis:latest || true
 
 after_script:
   # Check if the report file exists, then upload to DefectDojo
-  - if [ -f trivy-report.json ]; then echo "Report file exists"; else echo "Report file missing"; fi
+  - if [ -f trivy-travis-report.json ]; then echo "Report file exists"; else echo "Report file missing"; fi
   - echo "Uploading report to DefectDojo..."
   - |
-    if [ -f trivy-report.json ]; then
+    if [ -f trivy-travis-report.json ]; then
       curl -X POST \
         "${DEFECTDOJO_URL}/api/v2/import-scan/" \
         -H 'accept: application/json' \
         -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
         -H 'Content-Type: multipart/form-data' \
         -F "test=33" \
-        -F "file=@trivy-report.json;type=application/json" \
+        -F "file=@trivy-travis-report.json;type=application/json" \
         -F "scan_type=Trivy Scan" \
         -F "tags=sample" \
         --max-time 300 || echo "Failed to upload the report."
