Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,19 +11,30 @@ before_script:
 script:
   # Build Docker image
   - docker build -t trivy-travis:latest .
-  # Scan Docker image with Trivy and save the report in json format
-  - trivy image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy1-report.json trivy-travis:latest || true
+  # Scan Docker image with Trivy and save the report in JSON format
+  - trivy --debug image --exit-code 1 --severity HIGH,CRITICAL --format json -o trivy-report.json trivy-travis:latest || true
+  # Display contents of the report if it exists
+  - cat trivy-report.json || echo "No report generated by Trivy."
+  # Correct Permissions
+  - chmod 644 trivy-report.json
 
 
-  
 after_script:
+  # Check if the report file exists, then upload to DefectDojo
+  - if [ -f trivy-report.json ]; then echo "Report file exists"; else echo "Report file missing"; fi
   - echo "Uploading report to DefectDojo..."
   - |
-    curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
-      -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
-      -F "file=@trivy1-report.json" \
-      -F "scan_type=Trivy" \
-      -F "engagement=10" \
-      -F "product=33" \
-      -F "version=None" \
-      -F "notes=Trivy report uploaded from Travis CI"
+    if [ -f trivy-report.json ]; then
+      curl -X POST \
+        "${DEFECTDOJO_URL}/api/v2/import-scan/" \
+        -H 'accept: application/json' \
+        -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
+        -H 'Content-Type: multipart/form-data' \
+        -F "test=33" \
+        -F "file=@trivy-report.json;type=application/json" \
+        -F "scan_type=Trivy Scan" \
+        -F "tags=sample" \
+        --max-time 300 || echo "Failed to upload the report."
+    else
+      echo "Report file not found, skipping upload."
+    fi
