for today

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,21 +18,23 @@ script:
   # Check if the report file was created
   - if [ -f trivy1-report.json ]; then echo "Report generated successfully."; else echo "Report not generated."; fi
   # Ensure proper permissions for the report file
-  - chmod 644 trivy-report.json || echo "Report file is missing, skipping chmod."
+  - chmod 644 trivy-report.json || echo "Report file missing, skipping chmod."
 
 
   
 after_script:
   - echo "Uploading report to DefectDojo..."
   - |
-    curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
-      -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
-      -F "file=@trivy1-report.json" \
-      -F "scan_type=Trivy" \
-      -F "engagement=10" \
-      -F "product=33" \
-      -F "version=None" \
-      -F "notes=Trivy report uploaded from Travis CI";
-  else
-    echo "Report not found, skipping upload.";
-  fi
+    if [ -f trivy1-report.json ]; then
+      curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
+        -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
+        -F "file=@trivy1-report.json" \
+        -F "scan_type=Trivy" \
+        -F "engagement=10" \
+        -F "product=33" \
+        -F "version=None" \
+        -F "notes=Trivy report uploaded from Travis CI";
+    else
+      echo "Report not found, skipping upload.";
+    fi
+
